In [436]:
from sqlalchemy import create_engine
from sqlalchemy_utils import database_exists, create_database
from matplotlib.pyplot import imshow
import numpy as np
import fnmatch
import os
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import pylab
import pandas as pd
%matplotlib inline
pylab.rcParams['figure.figsize'] = (10.0, 8.0)


In [78]:
dbname = 'coffee_detai1'
username = 'emclinden'
engine = create_engine('postgres://%s@localhost/%s'%(username,dbname))
print engine.url

postgres://emclinden@localhost/coffee_detai1


In [79]:
sql_query = """
SELECT * FROM image_stats_del;
"""
data = pd.read_sql_query(sql_query,engine)

In [81]:
ntags_scale = (data.ntags - np.mean(data.ntags))/np.std(data.ntags)#,np.std(data.ntags)

In [88]:
bright_scale = (data.brightness - np.mean(data.brightness))/np.std(data.brightness)

In [91]:
comm_scale = (data.n_comments)

In [99]:
nc = data.n_comments.astype('str').astype('int').astype('float')
comm_scale = (nc - np.mean(nc)) / np.std(nc)

In [106]:
cont_scale = (data.contrast  - np.mean(data.contrast))/np.std(data.contrast)
nfavs = data.n_favs.astype('str').astype('int').astype('float')
nviews = data.n_views.astype('str').astype('int').astype('float')
y = nfavs / nviews

In [ ]:
data['brightness_scale']=bright_scale
data['contrast_scale'] = cont_scale
data['ntags_scale']=ntags_scale
data['comments_scale'] = comm_scale

In [109]:
data.to_sql('image_stats_del', engine, if_exists='replace')

In [111]:
from sklearn.linear_model import LinearRegression

In [173]:
data['result_y'] = y
data.to_sql('image_stats_del', engine, if_exists='replace')

In [411]:
query = "SELECT * from image_stats_del" #% patient
qr=pd.read_sql_query(query,con)
qr.head()

level_0  index   picture_id        user_id  \
0        0      0   6676961391    7891351@N05   
1        1      1  15444712858   81650523@N04   
2        2      2  15004931544   32157516@N05   
3        3      3  15600916982   56237114@N08   
4        4      4  15407506400  126314760@N06   

                                         static_file date_posted n_favs  \
0  https://farm8.staticflickr.com/7146/6676961391...  1326255301      0   
1  https://farm6.staticflickr.com/5608/1544471285...  1414320368     11   
2  https://farm4.staticflickr.com/3953/1500493154...  1414264980     23   
3  https://farm6.staticflickr.com/5608/1560091698...  1413982237      9   
4  https://farm6.staticflickr.com/5612/1540750640...  1413908972      1   

  n_views n_comments                                            tag_raw  \
0     232          2                                           {coffee}   
1    4122          1  {Coffee,Black,White,Cup,Mug,Mugg,Kaffe,Kaffemu...   
2    2184          5  {davide978,milano,milan,sempione,colazione,bre...   
3    1818          1  {Rijeka,hrvatska,croatia,summer,panorama,canon...   
4     180          0           {travel,coffee,cafe,kaffe,relax,terrace}   

     ...      longitude                                          hexcolors  \
0    ...     -73.959667  {#8d8457,#ddd7b3,#21170b,#a39969,#f6f3db,#b7ad...   
1    ...      14.860422  {#37392e,#d0c8ad,#6f6e57,#1f221b,#ece5cb,#928d...   
2    ...       9.172918  {#b7bbbd,#4e4638,#363328,#d8d9d7,#7f7e75,#9c9e...   
3    ...      14.455518  {#8b8b85,#22262c,#bee2f1,#11110e,#a8acab,#f7f1...   
4    ...      -3.708572  {#1b120e,#dad7d4,#83776a,#3d2e26,#ae9883,#9f6e...   

   brightness contrast  ntags  brightness_scale  contrast_scale  ntags_scale  \
0  169.645785      231      1          1.377681        0.760153    -1.098296   
1  131.139414      217     14          0.125026        0.498208     0.110684   
2  140.740993      197     25          0.437376        0.124001     1.133667   
3  167.636340      240     20          1.312312        0.928546     0.668675   
4  134.482411      208      6          0.233778        0.329815    -0.633304   

   comments_scale  result_y  
0       -0.194511  0.000000  
1       -0.273688  0.002669  
2        0.043020  0.010531  
3       -0.273688  0.004950  
4       -0.352865  0.005556  

[5 rows x 22 columns]

In [418]:
x1 = qr.brightness_scale; x2 = qr.contrast_scale; x3 = qr.ntags_scale; x4 = qr.comments_scale;
x =np.column_stack((x1,x2,x3,x4))
y = qr.result_y

In [419]:
xlearn = x[0:3000,:]
ylearn = y[0:3000]
xval = x[3000:,:]
yval = y[3000:]

In [422]:
clf = LinearRegression()
clf.fit (xlearn, ylearn)
print clf.coef_
print clf.intercept_

[  7.79905049e-05  -2.30374849e-04  -7.23382833e-04   2.20559201e-03]
0.00456432325076


In [ ]:
ypred = clf.predict(xval)

In [ ]:
a = [-0.41438529,  1.19049025,  0.76167307, -0.27368794]
sum(a*clf.coef_)+clf.intercept_

In [435]:
ypred

array([ 0.00440183,  0.00449345,  0.00441748,  0.00435785,  0.00453112,
        0.00485915,  0.00445823,  0.0042869 ,  0.00467032,  0.0044301 ,
        0.00455855,  0.00425233,  0.00445914,  0.0044728 ,  0.00456223,
        0.00444578,  0.00436329,  0.00480942,  0.00457799,  0.00444047,
        0.00442438,  0.00467466,  0.00447309,  0.00454939,  0.00449626,
        0.00446939,  0.00457515,  0.00458839,  0.00435624,  0.00442516,
        0.00456754,  0.00454727,  0.00440829,  0.00450634,  0.0045394 ,
        0.00466153,  0.00431427,  0.00462768,  0.00460082,  0.0045619 ,
        0.00467491,  0.00444498,  0.00422662,  0.00456047,  0.00452222,
        0.00425398,  0.00470377,  0.00461782,  0.00449847,  0.00429129,
        0.00477341,  0.00457907,  0.00453414,  0.00460335,  0.00446749,
        0.00440479,  0.0046842 ,  0.00430378,  0.00429582,  0.00445626,
        0.00456521,  0.00457801,  0.00461597,  0.00431677,  0.00465325,
        0.00477113,  0.00430199,  0.00449773,  0.00438832,  0.00

In [427]:
qr[3000:]

level_0  index   picture_id        user_id  \
3000     2996   2996   3495479747    7891351@N05   
3001     2997   2997   3495478813    7891351@N05   
3002     2998   2998   3492759380   91271949@N00   
3003     2999   2999   3485350117   36478297@N02   
3004     3000   3000   3482253714   48085290@N00   
3005     3001   3001   3479857835    9942688@N04   
3006     3002   3002   3472077944   85265114@N00   
3007     3003   3003   3471016215   36900230@N05   
3008     3004   3004   3467248584   34525698@N00   
3009     3005   3005   3466185743   85265114@N00   
3010     3006   3006   3457181541    9942688@N04   
3011     3007   3007   3456168596   94241007@N00   
3012     3008   3008   3454948084   31311541@N03   
3013     3009   3009   3452897110   39642806@N00   
3014     3010   3010   3450937185   81177269@N00   
3015     3011   3011   3451315588   31311541@N03   
3016     3012   3012   3445880930    9942688@N04   
3017     3013   3013   2605429646   22591797@N07   
3018     3015   3015   3437097909   30223382@N06   
3019     3016   3016   3436632071   21900243@N07   
3020     3017   3017   3429896995   80018919@N00   
3021     3018   3018   3416417861    7891351@N05   
3022     3019   3019   3385332862   78558463@N00   
3023     3020   3020   3416522942    9942688@N04   
3024     3021   3021   3412030926   37114731@N08   
3025     3022   3022   3411639896   37114731@N08   
3026     3023   3023   3270081699   35249320@N05   
3027     3024   3024   3411639290   37114731@N08   
3028     3025   3025   3406178106   29847315@N00   
3029     3026   3026   3404754930    9942688@N04   
...       ...    ...          ...            ...   
3835     3835   3835  16040773816   21251150@N04   
3836     3836   3836  15868222967   21801682@N00   
3837     3837   3837  15866862119  127986533@N08   
3838     3838   3838  15425080384   31676563@N05   
3839     3839   3839  15846120387   43588196@N05   
3840     3840   3840  15406979773   37578663@N02   
3841     3841   3841  16026634942   37578663@N02   
3842     3842   3842  15832748639   45454676@N00   
3843     3843   3843  15830331198   45454676@N00   
3844     3844   3844  16011110651   45454676@N00   
3845     3845   3845  15318882164   17993478@N00   
3846     3846   3846  15902392506  127116937@N02   
3847     3847   3847  15728200978   36826233@N00   
3848     3848   3848  15292506243   45454676@N00   
3849     3849   3849  15719828517   47461187@N08   
3850     3850   3850  15698939288   53929989@N03   
3851     3851   3851  15159853973   31693521@N08   
3852     3852   3852  15776485595   22058765@N02   
3853     3853   3853  15770219312   39908901@N06   
3854     3854   3854  15767246855   47461187@N08   
3855     3855   3855  15735525566   38501716@N08   
3856     3856   3856  21741956318   26706977@N04   
3857     3857   3857  21741732700   26706977@N04   
3858     3858   3858  20883358558   47461187@N08   
3859     3859   3859  20392809123   47461187@N08   
3860     3860   3860  20303766170   22254152@N08   
3861     3861   3861  20303446310   22254152@N08   
3862     3862   3862  20004180776   26706977@N04   
3863     3863   3863  20030448315   26706977@N04   
3864     3864   3864  19961955005   26706977@N04   

                                            static_file date_posted n_favs  \
3000  https://farm4.staticflickr.com/3640/3495479747...  1241325761      2   
3001  https://farm4.staticflickr.com/3317/3495478813...  1241325737      4   
3002  https://farm4.staticflickr.com/3638/3492759380...  1241219007      0   
3003  https://farm4.staticflickr.com/3301/3485350117...  1241010749      0   
3004  https://farm4.staticflickr.com/3557/3482253714...  1240888174      0   
3005  https://farm4.staticflickr.com/3375/3479857835...  1240851499      1   
3006  https://farm4.staticflickr.com/3545/3472077944...  1240611293      0   
3007  https://farm4.staticflickr.com/3374/3471016215...  1240603681      1   
3008  https://farm4.staticflickr.com/3517/3467248584...  1240447895      4   
3

In [208]:
newdf = pd.DataFrame()
newdf['picture_id'] = data.picture_id[3000:]
newdf['ypredict'] = ypred
newdf['yactual'] = yval

In [210]:
newdf.to_sql('valset_865', engine, if_exists='replace')

In [359]:
query = "SELECT * from image_stats_del" #% patient
query_results=pd.read_sql_query(query,engine)

In [360]:
a =query_results.loc[query_results['picture_id'].isin(['15159853973','2752376454','2813490117'])]

In [328]:
contrast = np.asarray(a.contrast_scale)
bright = np.asarray(a.brightness_scale)
ntags = np.asarray(a.ntags_scale)
ncomments = np.asarray(a.comments_scale)
x = np.column_stack((bright,contrast,ntags,ncomments));

array([[-0.371169  , -0.39988796, -0.81930083, -0.35286488],
       [ 0.38611964,  1.19049025, -0.81930083, -0.03615713],
       [ 0.40317285, -0.92377725,  0.38967921, -0.03615713]])

In [329]:
coef = [8.60414170e-05, -2.38880084e-04, -7.24585265e-04, 2.20345206e-03]
np.shape(x),np.shape(coef)

((3, 4), (4,))

In [368]:
r =np.dot(x,coef) 
r + intercept

array([ 0.0044456 ,  0.0048287 ,  0.00445921])

In [358]:
intercept = 0.00456587911375
-0.00012028 + 0.00456587911375
0.00026282 + 0.00456587911375

0.0048286991137499995

In [348]:
aa =df.loc[df['picture_id'].isin(['15159853973','2752376454','2813490117'])]

In [349]:
aa

picture_id  ypredict   yactual
3152   2813490117  0.065256  0.049873
3242   2752376454  0.001134  0.000000
3851  15159853973  0.004459  0.004228

In [ ]:
dbname = 'coffee_detai1'
username = 'emclinden'
engine = create_engine('postgres://%s@localhost/%s'%(username,dbname))
print engine.url

query = "SELECT * from image_stats_del" #% patient
query_results=pd.read_sql_query(query,engine)

In [380]:
import psycopg2

user = 'emclinden' #add your username here (same as previous postgreSQL)            
host = 'localhost'
dbname = 'coffee_detai1'
db = create_engine('postgres://%s%s/%s'%(user,host,dbname))
con = None
con = psycopg2.connect(database = dbname, user = user)

In [384]:
query = "SELECT * from image_stats_del" #% patient
qr=pd.read_sql_query(query,con)

In [386]:
qr

level_0  index   picture_id        user_id  \
0           0      0   6676961391    7891351@N05   
1           1      1  15444712858   81650523@N04   
2           2      2  15004931544   32157516@N05   
3           3      3  15600916982   56237114@N08   
4           4      4  15407506400  126314760@N06   
5           5      5  15397619317    8096730@N04   
6           6      6  15186661968   69861074@N00   
7           7      7  15138977569   82684724@N00   
8           8      8  15040731800   38501716@N08   
9           9      9  15154582916  100016856@N08   
10         10     10  14988376909   38501716@N08   
11         11     11  15103855655   99931792@N00   
12         12     12  14893141427  125880512@N08   
13         13     13  14972267132   10788645@N03   
14         14     14  14573125140   55311638@N00   
15         15     15  14717551036   28458776@N04   
16         16     16   8465956569   43671648@N04   
17         17     17  14532503998   37578663@N02   
18         18     18  14676114774   55311638@N00   
19         19     19   8462765001   47477544@N08   
20         20     20  14321745817   55311638@N00   
21         21     21  14215712597   53874803@N02   
22         22     22  14317152932   55311638@N00   
23         23     23  14332183693   55311638@N00   
24         24     24  14289658921   55311638@N00   
25         25     25  14320831623   83374054@N03   
26         26     26  14038151290   55311638@N00   
27         27     27  14128130434   38501716@N08   
28         28     28  14045502266   30786640@N00   
29         29     29  13645122304  100754490@N02   
...       ...    ...          ...            ...   
3835     3835   3835  16040773816   21251150@N04   
3836     3836   3836  15868222967   21801682@N00   
3837     3837   3837  15866862119  127986533@N08   
3838     3838   3838  15425080384   31676563@N05   
3839     3839   3839  15846120387   43588196@N05   
3840     3840   3840  15406979773   37578663@N02   
3841     3841   3841  16026634942   37578663@N02   
3842     3842   3842  15832748639   45454676@N00   
3843     3843   3843  15830331198   45454676@N00   
3844     3844   3844  16011110651   45454676@N00   
3845     3845   3845  15318882164   17993478@N00   
3846     3846   3846  15902392506  127116937@N02   
3847     3847   3847  15728200978   36826233@N00   
3848     3848   3848  15292506243   45454676@N00   
3849     3849   3849  15719828517   47461187@N08   
3850     3850   3850  15698939288   53929989@N03   
3851     3851   3851  15159853973   31693521@N08   
3852     3852   3852  15776485595   22058765@N02   
3853     3853   3853  15770219312   39908901@N06   
3854     3854   3854  15767246855   47461187@N08   
3855     3855   3855  15735525566   38501716@N08   
3856     3856   3856  21741956318   26706977@N04   
3857     3857   3857  21741732700   26706977@N04   
3858     3858   3858  20883358558   47461187@N08   
3859     3859   3859  20392809123   47461187@N08   
3860     3860   3860  20303766170   22254152@N08   
3861     3861   3861  20303446310   22254152@N08   
3862     3862   3862  20004180776   26706977@N04   
3863     3863   3863  20030448315   26706977@N04   
3864     3864   3864  19961955005   26706977@N04   

                                            static_file date_posted n_favs  \
0     https://farm8.staticflickr.com/7146/6676961391...  1326255301      0   
1     https://farm6.staticflickr.com/5608/1544471285...  1414320368     11   
2     https://farm4.staticflickr.com/3953/1500493154...  1414264980     23   
3     https://farm6.staticflickr.com/5608/1560091698...  1413982237      9   
4     https://farm6.staticflickr.com/5612/1540750640...  1413908972      1   
5     https://farm6.staticflickr.com/5606/1539761931...  1413816439      2   
6     https://farm4.staticflickr.com/3850/1518666196...  1411854385     19   
7     https://farm4.staticflickr.com/3869/1513897756...  1411494024     17   
8     https://farm4.staticflickr.com/3878/1504073180...  1410633692     53   
9